# base path of the gallery on the filesystem
BasePath = "images/"

# log file location
LogFile = "redcarpet.log"

# base url
# if wanting to mount redcarpet under a subdirectory, set it to whatever you want
# if you want it at the root, set it to "/"
# trailing slash is necessary
BaseURL = "/"

# where go server should listen for fcgi requests
ListenAddress = "127.0.0.1:9003"
